//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendMail
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int UserId { get; set; }
        public string UserMail { get; set; }
        public string UserPassword { get; set; }
    }

}
